### ISSUE TITLE
UA-Parser Test Suite errors

### ISSUE THREAD

**Issue by mimmi20** [diablomedia/useragent-parser-comparison#78]
The Test Suite for the UA-Parser is loaded via npm. In this package the tests are gone.

**Comment by jaydiablo** [comment]
Yeah, seems that they added the two test directories we use to the `.npmignore` file.

I've tried looking around to see if it's possible to have NPM bypass the `.npmignore` file, but not finding anything.  The only solution I can think of at the moment is to `git clone` the repo instead of using npm for that one.
